### ISSUE TITLE
Issues with XGBoostEstimator cell

### ISSUE THREAD

**Issue by tunguz** [BogdanCojocar/medium-articles#1]
Hi there,

first, thank you for a great Medium post and for this repository. I am new to PySpark, and am trying to run your code. It all works fine util I get to `xgboost = XGBoostEstimator(...` cell. When I try to run it, i get the following error message:

`TypeError: 'JavaPackage' object is not callable`

If you have any ides why this might be the case, or what I could do to resolve this issue, it would be very helpful.

Thanks,

Bojan

**Comment by BogdanCojocar** [comment]
Hi @tunguz ,

Please have a look at this PR as the XGBoost wrapper is in an alpha state and is constantly changes:
https://github.com/dmlc/xgboost/issues/1698

Cheers,
Bogdan
